addpath(genpath('/storage/gablab001/data/genus/GIT/genus/bayes/matlab'));
load('{}', 'I', 'G', 'Z', 'colnames');
load('{}', 'train', 'test');
idxs=train.train_{};
G=single(G);
G=G(idxs, :);
Z=Z(idxs, :);
yI=I(:, {});
yI=yI(idxs, :);
sigma=(0.2:0.08:1);
sa=(0.025:0.025:0.4);
fit=varbvs(G,Z,yI,colnames,[],struct('logodds',-5:0.25:-3));
w=fit.w;
alpha=fit.pip;
mu=fit.mu;
lnZ_weighted=fit.logw(:)'*w(:);
lnZ=fit.logw;
beta=fit.beta;
save('{}','alpha','beta','w','mu','lnZ','lnZ_weighted');
