load('{}', 'I', 'G', 'colnames');
load('{}', 'train', 'test');
idxs=train.train_{};
G=single(G);
G=G(idxs, :);
yI=I(:, {});
yI=yI(idxs, :);
sigma=(0.2:0.08:1);
sa=(0.025:0.025:0.4);
fit=varbvs(G,[],yI,colnames,[],struct('logodds',-5:0.25:-3));
w=normalizelogweights(fit.logw);
PIP=fit.alpha * w(:);
mu=fit.mu;
alpha=fit.alpha;
save('{}','PIP','w','alpha','mu');
